### ISSUE TITLE
No module name `plastid`

### ISSUE THREAD

**Issue by kerfar** [joshuagryphon/plastid#28]
Hello,
I installed plastid, have updated numpy, pysam and Cython.
when in python I type `import plastid` I always get this message:
Traceback (most recent call last):
  File "< stdin >", line 1, in < module >
ImportError: No module named 'plastid'

What`s wrong and what can I do with it?
Thanks.

**Comment by QinglvWei** [comment]
Hi kerhar
I had the same problem with you when I first installed plastid package in Mac from Bioconda or directly from PyPI . Then I constructed a virtual environment using pyenv.
the first step is create a new directory in order to run plastid and pyenv; 
and then install pyenv:
  brew update
  brew install pyenv
after environment variables setting, plastid can be installed using the following commands:
  pyenv install 2.7.15
  pip install numpy pysam cython
  pip install plastid
you can test with the following commands in terminal:
  python 
  import plastid

**Comment by kerfar** [comment]
Thanks, but I have Linux, not Mac.
We tried something similar, plastid was installed in envs/plastid.
When in python tried import plastid, got this:
(plastid) lrge@128-BioLinux:~$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>import plastid
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/lrge/miniconda3/envs/plastid/lib/python3.6/site-packages/plastid/__init__.py", line 44, in <module>
   from plastid.genomics.genome_array import (BAMGenomeArray,
 File "/home/lrge/miniconda3/envs/plastid/lib/python3.6/site-packages/plastid/genomics/genome_array.py", line 215, in <module>
   from plastid.genomics.map_factories import *
 File "libchtslib.pxd", line 2590, in init plastid.genomics.map_factories
ValueError: pysam.libchtslib.HTSFile has the wrong size, try recompiling. Expected 88, got 80

Any idea what the hell is this and what to do with it?
Thanks!

**Comment by joshuagryphon** [comment]
Hi folks-

@kerfar - I can help debug if you can send some more information. Can you tell me:

1. How did you install (via `pip`? via `conda`? from source?)? What exactly did you type to install?

2. What exactly did you type to import (from the time you open the terminal, until and including the `import` statement in Python)

3. What version of `pysam` do you have installed inside your `conda` environment? 

4. What version of `pysam` do you have installed in your system and/or user environments?

Given that you're using `conda`, I think you're seeing is a replication of issues #2 and #4. The phenomenon in those issues is that, when installing under `conda` (not supported in plastid 0.4.8 release), `conda` fails to pass environment variables from the conda environment to the environment under which Plastid's c extensions are built. As a result, build and install complete successfully, but upon import, the compiled extensions report the wrong size, because of mismatches been library versions in the conda environment vs the build environment. This is very much a conda bug, which affects other packages as well, and may be what you're seeing here.

You may be able to get things working instead by any of the following:

1. Installing inside a `virtualenv` and abandoning `conda`. This may get a little complicated as `conda` can interfere with a number of things

2. Try installing from `bioconda` (using recipe from @lparsons ), if this happens to be different from what you tried before

**Comment by lparsons** [comment]
@kerfar I updated the plastid package in bioconda to address the second issue you referred to (https://github.com/joshuagryphon/plastid/issues/28#issuecomment-499476178). Try a fresh conda environment and [installing plastid using the bioconda package](https://bioconda.github.io/recipes/plastid/README.html).

**Comment by joshuagryphon** [comment]
Hi @kerfar , did Lance's suggestion resolve your issue? Are we able to close this?

Cheers,
Josh
