### ISSUE TITLE
Question on --gff_transcript_types and --mask_gff_transcript_types

### ISSUE THREAD

**Issue by Zhuxitong** [joshuagryphon/plastid#38]
Hello, 
In the doc, the parameter
```
--gff_transcript_types  GFF_TRANSCRIPT_TYPES [GFF_TRANSCRIPT_TYPES ...] 	GFF3 feature types to include as transcripts, even if no exons are present (for GFF3 only; default: use SO v2.5.3 specification)
```
and
```
--mask_gff_transcript_types  MASK_GFF_TRANSCRIPT_TYPES [MASK_GFF_TRANSCRIPT_TYPES ...] 	GFF3 feature types to include as transcripts, even if no exons are present (for GFF3 only; default: use SO v2.5.3 specification)
``` 
have exactly same explation. So what's the difference bewteen them? --gff_exon_types and --gff_cds_types also have same problem.

**Comment by joshuagryphon** [comment]
Hi @Zhuxitong ,

These parameters have similar options and explanations because they both determine how annotation files are handled. 

The difference is, the `mask-` versions, specifically govern regions of the genome that you would like to exclude from analysis. For example, if you supply `--mask_annotation_file foo.gff`, any region in `foo.gff` will not be excluded in your data.

Some details appear here: [Excluding (masking) regions of the genome](https://plastid.readthedocs.io/en/latest/examples/using_masks.html?highlight=mask%20file).

Please take a look at the documentation, and let me know if you have any questions.

Cheers,
Josh
