### ISSUE TITLE
logging dependency should be remove from setup.py when installing with Python3

### ISSUE THREAD

**Issue by EricDeveaud** [joshuagryphon/plastid#43]
Hello, 
logging is part of the standard library in python3

having setup.py requires for 'logging' causes problems while logging is grabbed from pypi and as logging module from pypi is python2 syntax.

regards

Eric

**Comment by joshuagryphon** [comment]
Thank you for filing your bug report. I'm a little confused here because I don't think `plastid` ever depended upon `logging`, and tests have been passing under various versions of Python 3 for several years now. Possibly `logging` was being imported by an outdated dependency?

I can however say this issue is resolved, in the `develop` branch. At present, we support Python 3.6 and 3.9, and all tests pass in fresh environments.
