### ISSUE TITLE
the bam file choose

### ISSUE THREAD

**Issue by z626093820** [joshuagryphon/plastid#47]
when i use star to alignment, i can get the bam file compared to the genome(01Aligned.sortedByCoord.out.bam) and the bam file compared to the transcript(01Aligned.toTranscriptome.out.bam), Which one should I choose for psite script analysis?
thank you!

**Comment by joshuagryphon** [comment]
Hi @z626093820 ,
I hope you managed to find a solution long ago, but in case still relevant, you can use either BAM file, but you need the BAM file to match whatever gene annotation you're also using. My guess is that your gene annotations will be in genome, rather than transcript coordinates, so I'd recommend using the genome file.

Best,
Josh
