### ISSUE TITLE
Problem install plastid 'no attribute 'PileupColumn'

### ISSUE THREAD

**Issue by Markestine** [joshuagryphon/plastid#49]
Hello,

I tried to install plastid in environment conda whith pysam, cython et numpy.

When I installed with pip3 (python3.8) the plastid package (v0.5.1) everithing was fine.
But when I try to used this package, I have this error
  File "/usr/local/lib/python3.8/dist-packages/plastid/genomics/genome_array.py", line 215, in <module>
    from plastid.genomics.map_factories import *
  File "plastid/genomics/map_factories.pyx", line 1, in init plastid.genomics.map_factories
AttributeError: module 'pysam.libcalignmentfile' has no attribute 'PileupColumn'

Do you know, where come from my issue?

Thanks a lot in advance,

**Comment by joshuagryphon** [comment]
Hi @Markestine ,
It looks like you might have installed in a `conda` environment, but may be attempting to import the package outside the `conda` environment. The path `/usr/local/lib/python3.8/dist-packages/plastid/genomics/genome_array.py` points to a system install ( `conda` paths usually mention `anaconda` in the name.), so for this error to have arisen I think you must have attempted to import from outside the `conda` environment.

Solutions here would be:
* Do a system install (outside conda)
* Alternatively, run inside your conda environment

**Comment by joshuagryphon** [comment]
Verified that this is caused by mismatching environments, not an internal bug.

An additional case where this can come up is if stale Cython-generated C files are compiled after the Pysam libraries they will be linked against have changed. In this case, regenerating the C files (e.g. via `python setup.py build_ext --inplace --recythonize`) will resolve
